version: '3.8'

services:
  app:
    build:
      context: .
    volumes:
      - .:/var/www
    expose:
      - "9000"

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
